### ISSUE TITLE
"Unknown column 'password'" error on MySQL 5.7.9

### ISSUE THREAD

**Issue by scomnoob** [pmachapman/mysqltuner#12]
win 2012r2
mysql 5.7.9

It fails with very strange error 

MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'password' in 'where clause'
  at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
  at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
  at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
  at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
  at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
  at MySqlTuner.FormMain.SecurityRecommendations() in c:\Users\Peter\Documents\Visual Studio 2013\Projects\MySQLTuner\MySQLTuner\FormMain.cs:line 596
  at MySqlTuner.FormMain.BackgroundWorker_DoWork(Object sender, DoWorkEventArgs e) in c:\Users\Peter\Documents\Visual Studio 2013\Projects\MySQLTuner\MySQLTuner\FormMain.cs:line 388

![error](https://cloud.githubusercontent.com/assets/13706354/10963951/ff386bd8-83b4-11e5-9f92-379fb574029b.JPG)

**Comment by scomnoob** [comment]
any news?

**Comment by pmachapman** [comment]
I haven't yet had a chance to look at the bug - I have quite on at the moment. I will update this issue when I get a chance to look into it.

**Comment by alefort** [comment]
I'm also experiencing this on mysql 5.7.9

**Comment by pmachapman** [comment]
I am in the process of upgrading my server to MySQL 5.7, and reading the docs it turns out that the password field is now called authentication_string. Go figure.

I have written a fix, and it is in commit 04057512146b29aca71b75e1fa3836a2d6a86897
