### ISSUE TITLE
Crash when connecting to a MySQL 4.1 database

### ISSUE THREAD

**Issue by pmachapman** [pmachapman/mysqltuner#16]
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySqlTuner.MySqlServer.get_Version() in C:\Users\peter\Source\Repos\mysqltuner\MySQLTuner\MySqlServer.cs:line 275
   at MySqlTuner.MySqlServer.Load() in C:\Users\peter\Source\Repos\mysqltuner\MySQLTuner\MySqlServer.cs:line 482
   at MySqlTuner.TuningCalculator.Calculate(MySqlServer server) in C:\Users\peter\Source\Repos\mysqltuner\MySQLTuner\TuningCalculator.cs:line 138

**Comment by pmachapman** [comment]
Fixed in 1b5ab197c6e52626a06ff6103037f58b875c5b53
