### ISSUE TITLE
Support early mysql 4.0.18 issue Again

### ISSUE THREAD

**Issue by ayuen99** [pmachapman/mysqltuner#17]
Hi,

I found an error during testing another mysql server.

System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue(Int32 index, Boolean checkNull)
   at MySql.Data.MySqlClient.MySqlDataReader.GetString(Int32 i)
   at MySqlTuner.MySqlServer.Load() in C:\Users\Peter.Chapman\Source\Repos\mysqltuner\MySQLTuner\MySqlServer.cs:line 586
   at MySqlTuner.TuningCalculator.Calculate(MySqlServer server) in C:\Users\Peter.Chapman\Source\Repos\mysqltuner\MySQLTuner\TuningCalculator.cs:line 138

**Comment by pmachapman** [comment]
Hmm, looks like an odd one. Are there many databases on the server? It looks like it is crashing on the output of the SHOW TABLE STATUS FROM _your_database_name_ query.

Are you able to run SHOW TABLE STATUS FROM  _your_database_name_ for each database on your server, including the mysql database, and send me the output as a text file or CSV file?

Also, are you connecting as the root user?

**Comment by pmachapman** [comment]
I've written a fix for the crash that you have been having: https://github.com/pmachapman/mysqltuner/releases/download/0.8.3/MySQLTuner-0.8.3-net20-connector-517.zip. Please let me know if this fixes the issue for you.
